# Generated by Django 5.1.7 on 2025-04-04 16:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Привычка должна выполняться минимум 1 раз в неделю"
                    ),
                    django.core.validators.MaxValueValidator(
                        7,
                        message="Привычка не может выполняться реже, чем раз в неделю",
                    ),
                ],
                verbose_name="Периодичность (раз в неделю)",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_time", models.DateTimeField(verbose_name="Время отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Уведомления включены"),
                            ("deactivated", "Уведомления отключены"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус подписки",
                    ),
                ),
                ("notification_count", models.IntegerField(default=0)),
                ("last_notification", models.DateTimeField(blank=True, null=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="tracker.habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
    ]
