# Generated by Django 5.1.7 on 2025-04-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_habit_frequency_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="days_of_week",
            field=models.CharField(
                default="1,2,3,4,5,6,7",
                help_text="Дни недели в формате 1,2,3,4,5,6,7 (где 1 - понедельник)",
                max_length=20,
                verbose_name="Дни недели для отправки",
            ),
        ),
    ]
