# Generated by Django 5.1.7 on 2025-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_subscription_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="send_time",
            field=models.TimeField(verbose_name="Время отправки"),
        ),
    ]
