# Generated by Django 5.2 on 2025-05-06 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_subscription_send_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_time",
            field=models.PositiveIntegerField(
                help_text="Время на выполнение не должно превышать 120 секунд",
                validators=[django.core.validators.MaxValueValidator(120)],
                verbose_name="Время на выполнение (в минутах)",
            ),
        ),
    ]
